{% set name = "dxtb" %}
{% set version = "0.4.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dxtb-{{ version }}.tar.gz
  sha256: 80bba3b3c5c779297d8be3390afde962a1a0ac3971028eaeb5bb5a9b05f6e227

build:
  entry_points:
    - dxtb = dxtb._src.cli:console_entry_point
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - h5py
    - numpy
    - pydantic >=2.0.0
    - scipy
    - tad-dftd3 ==0.6.0
    - tad-dftd4 ==0.8.0
    - tad-mctc ==0.7.0
    - tad-multicharge ==0.5.0
    - tomli
    - tomli-w
    - pytorch >=1.11.0,<3
    - typing-extensions

test:
  imports:
    - dxtb
  commands:
    - pip check
    - dxtb --version
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Fully Differentiable Approach to Extended Tight Binding
  home: https://github.com/grimme-lab/dxtb
  dev_url: https://github.com/grimme-lab/dxtb
  doc_url: https://dxtb.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marvinfriede
